#!/usr/local/bin/python3

import os
import argparse

from generator.parser import DataParser

def main():
    parser = argparse.ArgumentParser()
    #parser.add_argument("input_data_file", nargs="?", type=argparse.FileType("r"), default=sys.stdin)
    parser.add_argument("--input_data_file", default="fr_ca/projects.xml", type=str)
    args = parser.parse_args()
    parser = DataParser(args.input_data_file)
    parser.generate_projects_summary(os.path.join("generated","projects_summary.md"))

if __name__ == '__main__':
    main()