#!/usr/local/bin/python3

import os
import argparse

from generator.parser import DataParser

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_data_file", default="fr_ca/projects.xml", type=str)
    parser.add_argument("--output_dir", type=str)
    parser.add_argument("-3", "--three_cols", action="store_true")
    parser.add_argument("--details", action="store_true", help="Add an extra grouped details section at the end of the document.")
    args = parser.parse_args()
    parser = DataParser(args.input_data_file)
    parser.generate_projects_pages(args.output_dir,  args.details)


if __name__ == '__main__':
    main()